---
- hosts: all
  sudo: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes

- hosts: web
  sudo: yes
  tasks:
    - name: install nginx
      apt: name=nginx state=present

- hosts: db
  sudo: yes
  tasks:
    - name: install mariadb
      apt: name={{ item }} state=present
      with_items:
        - mariadb-server
        - mariadb-client
